name: Build and Test

on: 
  push: 
    branches: 
      - main

jobs: 
  scripts-unit-tests: 
    name: Scripts Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Scripts
    steps: 
    - uses: actions/checkout@v3
      name: GitHub Checkout
    - name: Docker Install Unit Test
      run: ./installdocker.sh
    - name: Terraform Install Unit Test
      run: ./installterraform.sh