name: Build and Test

on: 
  push: 
    branches: 
      - main
  pull_request:
    types: [opened, reopened]
    branches: 
      - main

jobs: 
  docker-unit-tests: 
    name: Docker Install Unit Test
    runs-on: ubuntu-latest
    environment: Staging
    defaults:
      run:
        shell: bash
        working-directory: ./Scripts
    steps: 
    - uses: actions/checkout@v3
      name: GitHub Checkout
    - name: Docker Install Unit Test
      run: sudo ./installdocker.sh

  terraform-unit-tests: 
    name: Terraform Install Unit Test
    runs-on: ubuntu-latest
    environment: Staging
    defaults:
      run:
        shell: bash
        working-directory: ./Scripts
    steps: 
    - uses: actions/checkout@v3
      name: GitHub Checkout
    - name: Terraform Install Unit Test
      run: sudo ./installterraform.sh