name: Init RDS Database Staging

on: 
  workflow_dispatch: 
    branches: 
      - STAGING

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  MYSQL_ROOT_USER: ${{ secrets.MYSQL_ROOT_USER }}
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

jobs: 
  init-remote-statefile: 
    name: Init Remote Statefile S3 using Terraform
    runs-on: ubuntu-latest
    environment: Staging
    defaults:
      run:
        shell: bash
        working-directory: ./Terraform/Database_Staging
    steps: 
    - uses: actions/checkout@v3
      name: GitHub Checkout
    - name: Install jq
      run: sudo apt update && sudo apt install jq -y
    - name: Set AWS_Region
      run: echo "AWS_REGION=$(jq .region -r .config.json)" >> $GITHUB_ENV
      working-directory: .
    - name: Replace Placeholder MYSQL_DATABASE
      run: python3 ../../Utilities/replacer.py terraform.tfvars terraform.tfvars ~bucketname~ $MYSQL_DATABASE
    - name: Replace Placeholder MYSQL_ROOT_USER
      run: python3 ../../Utilities/replacer.py terraform.tfvars terraform.tfvars ~tablename~ $MYSQL_ROOT_USER
    - name: Replace Placeholder MYSQL_ROOT_PASSWORD
      run: python3 ../../Utilities/replacer.py terraform.tfvars terraform.tfvars ~tablename~ $MYSQL_ROOT_PASSWORD
    - name: Replace Placeholder AWS_REGION
      run: python3 ../../Utilities/replacer.py terraform.tfvars terraform.tfvars ~region~ $AWS_REGION
    - name: Terraform Init
      run: terraform init
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Apply
      run: terraform apply --auto-approve