name: Release Cluster West

on: 
  workflow_dispatch: 
    branches: 
      - main

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  TABLE_NAME: ${{ secrets.TABLE_NAME }}
  AWS_ECS_ARN: ${{ secrets.AWS_ECS_ARN }}
  MYSQL_DB_URL: db-app.team.franns.net

#This workflow requires Docker, Terraform and jq which comes Pre-Installed on Github Runners

jobs: 
  release-cluster: 
    name: Release Cluster using Terraform
    runs-on: ubuntu-latest
    environment: ProductionW
    defaults:
      run:
        shell: bash
        working-directory: ./Terraform/Cluster_ProductionW
    steps: 
    - uses: actions/checkout@v3
      name: GitHub Checkout

    - name: Set AWS_Region ENV
      run: echo "AWS_REGION=us-west-1" >> $GITHUB_ENV
      working-directory: .

    - name: Replace Backend Placeholder BUCKET_NAME
      run: python3 ../../Utilities/replacer.py backend.tf backend.tf ~bucketname~ $BUCKET_NAME

    - name: Replace Backend Placeholder TABLE_NAME
      run: python3 ../../Utilities/replacer.py backend.tf backend.tf ~tablename~ $TABLE_NAME

    - name: Replace Backend Placeholder AWS_REGION
      run: python3 ../../Utilities/replacer.py backend.tf backend.tf ~region~ $AWS_REGION

    - name: Replace Placeholder AWS_REGION
      run: python3 ../../Utilities/replacer.py terraform.tfvars terraform.tfvars ~region~ $AWS_REGION

    - name: Replace Placeholder AWS_ECS_ARN
      run: python3 ../../Utilities/replacer.py main.tf main.tf ~awsecsarn~ $AWS_ECS_ARN

    - name: Replace Placeholder MYSQL_DB_URL
      run: python3 ../../Utilities/replacer.py main.tf main.tf ~mysqldburl~ $MYSQL_DB_URL

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Destroy
      run: terraform destroy --auto-approve